tap "homebrew/core"
tap "homebrew/boneyard"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"
cask "java"
cask "xquartz"
brew "atlassian-cli"
brew "aws-elasticbeanstalk"
brew "gdbm"
brew "sqlite"
brew "awscli"
brew "cmake"
brew "cocoapods"
brew "docker"
brew "icu4c"
brew "hicolor-icon-theme"
brew "libnet"
brew "ettercap", args: ["with-gtk+3"]
brew "exiftool"
brew "ffmpeg", args: ["with-fdk-aac", "with-x265"]
brew "git"
brew "gnu-getopt"
brew "git-flow-avh"
brew "go"
brew "graphviz"
brew "gsettings-desktop-schemas"
brew "hugo"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick"
brew "kubernetes-cli"
brew "kops"
brew "libav"
brew "libevent"
brew "links"
brew "makedepend"
brew "mas"
brew "maven"
brew "mitmproxy"
brew "ncdu"
brew "nmap"
brew "node"
brew "p7zip"
brew "postgresql", restart_service: true
brew "pstree"
brew "python"
brew "rename"
brew "ruby"
brew "tmux"
brew "tree"
brew "unrar"
brew "utf8proc"
brew "wget"
brew "yuicompressor"
brew "zsh"
brew "zsh-completions"
cask "adobe-creative-cloud"
cask "atom"
cask "charles"
cask "cyberduck"
cask "docker"
cask "evernote"
cask "firefox"
cask "google-chrome"
cask "gpg-suite"
cask "gramps"
cask "ichm"
cask "inkscape"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keepassxc"
cask "microsoft-office"
cask "onedrive"
cask "skype"
cask "slack"
cask "telegram"
cask "textmate"
cask "vmware-fusion"
cask "whatsapp"
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
