tap "homebrew/boneyard"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
cask "java"
cask "xquartz"
brew "atlassian-cli"
brew "gdbm"
brew "sqlite"
brew "aws-elasticbeanstalk"
brew "python"
brew "awscli"
brew "cmake"
brew "cocoapods"
brew "docker", link: false
brew "pkg-config"
brew "gsettings-desktop-schemas"
brew "icu4c"
brew "hicolor-icon-theme"
brew "libnet"
brew "ettercap", args: ["with-gtk+3"]
brew "exiftool"
brew "libevent"
brew "ffmpeg"
brew "git"
brew "gnu-getopt"
brew "git-flow-avh"
brew "go"
brew "gpac"
brew "graphviz"
brew "hugo"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick"
brew "kubernetes-cli"
brew "kops"
brew "libav"
brew "links"
brew "makedepend"
brew "mas"
brew "maven"
brew "mitmproxy"
brew "ncdu"
brew "nmap"
brew "node", link: false
brew "p7zip"
brew "postgresql", restart_service: true
brew "pstree"
brew "pyenv"
brew "rename"
brew "ruby"
brew "tmux"
brew "tree"
brew "unrar"
brew "utf8proc"
brew "wget"
brew "yarn"
brew "yuicompressor"
brew "zsh"
brew "zsh-completions"
cask "atom"
cask "charles"
cask "cyberduck"
cask "darktable"
cask "docker"
cask "evernote"
cask "firefox"
cask "geekbench"
cask "geotag"
cask "google-chrome"
cask "gpg-suite"
cask "gramps"
cask "ichm"
cask "inkscape"
cask "iterm2"
cask "java"
cask "jetbrains-toolbox"
cask "keepassxc"
cask "microsoft-office"
cask "obs"
cask "onedrive"
cask "signal"
cask "skype"
cask "skype-for-business"
cask "slack"
cask "snagit"
cask "steam"
cask "telegram"
cask "textmate"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "xmind"
cask "xquartz"
cask "deezer"
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To-Do", id: 1274495053
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
